// Hip implant grid configuration
// Built from actual catalog items

export const HIP_SECTIONS = [
  {
    id: 'hip_stem',
    label: 'Stems',
    fixationGroups: [
      {
        label: 'Cemented',
        variants: [
          { id: 'accolade_c_127', label: 'Accolade C 127°' },
          { id: 'accolade_c_132', label: 'Accolade C 132°' },
        ],
        sizes: ['2', '3', '4', '5', '6', '7'],
      },
      {
        label: 'Pressfit',
        variants: [
          { id: 'accolade_ii_127', label: 'Accolade II 127°' },
          { id: 'accolade_ii_132', label: 'Accolade II 132°' },
          { id: 'insignia_standard', label: 'Insignia Standard' },
          { id: 'insignia_high', label: 'Insignia High' },
        ],
        sizes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'],
      },
    ],
    sizes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'],
  },
  {
    id: 'hip_cup',
    label: 'Cups',
    fixationGroups: null,
    rowLabel: 'Type',
    sizeLabel: '',
    variants: ['trident_ii_tritanium', 'trident_psl_ha'],
    sizes: ['42A', '44B', '46C', '48D', '50D', '52E', '54E', '56F', '58F', '60G', '62G', '64H', '66H'],
    sizesByVariant: {
      'trident_psl_ha': ['46D', '50E', '52E'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_liner_x3_0',
    label: 'Liners — X3 0°',
    fixationGroups: null,
    rowLabel: 'ID',
    sizeLabel: '',
    variants: ['22mm', '28mm', '32mm', '36mm', '40mm', '44mm'],
    sizes: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    sizesByVariant: {
      '22mm': ['A', 'B', 'I'],
      '28mm': ['D', 'F'],
      '32mm': ['B', 'C', 'J'],
      '36mm': ['E', 'F', 'G', 'H'],
      '40mm': ['E', 'F', 'G', 'H'],
      '44mm': ['H'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_liner_x3_10',
    label: 'Liners — X3 10°',
    fixationGroups: null,
    rowLabel: 'ID',
    sizeLabel: '',
    variants: ['22mm', '26mm', '28mm', '32mm', '36mm'],
    sizes: ['B', 'D', 'E', 'F', 'G', 'H', 'J'],
    sizesByVariant: {
      '22mm': ['B'],
      '26mm': ['E', 'J'],
      '28mm': ['J'],
      '32mm': ['D', 'E', 'F'],
      '36mm': ['E', 'F', 'G', 'H'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_liner_x3_ecc',
    label: 'Liners — X3 Eccentric 0°',
    fixationGroups: null,
    rowLabel: 'ID',
    sizeLabel: '',
    variants: ['28mm', '32mm', '36mm'],
    sizes: ['C', 'D', 'E', 'F', 'G', 'H', 'I'],
    sizesByVariant: {
      '28mm': ['C'],
      '32mm': ['D'],
      '36mm': ['E', 'F', 'G', 'H', 'I'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_liner_mdm_cocr',
    label: 'Liners — MDM CoCr',
    fixationGroups: null,
    rowLabel: '',
    sizeLabel: '',
    variants: ['mdm_cocr'],
    sizes: ['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
  },
  {
    id: 'hip_liner_mdm_x3',
    label: 'Liners — MDM X3',
    fixationGroups: null,
    rowLabel: 'ID',
    sizeLabel: '',
    variants: ['22mm', '28mm'],
    sizes: ['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    sizesByVariant: {
      '22mm': ['C', 'D'],
      '28mm': ['E', 'F', 'G', 'H', 'I', 'J'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_head_delta',
    label: 'Heads — Delta Ceramic',
    fixationGroups: null,
    rowLabel: 'Diameter',
    sizeLabel: '',
    variants: ['28mm', '32mm', '36mm'],
    sizes: ['-5', '-4', '-2.7', '-2.5', '0', '+2.5', '+4', '+5', '+7.5'],
    sizesByVariant: {
      '28mm': ['-4', '-2.7', '0', '+4'],
      '32mm': ['-4', '0', '+4'],
      '36mm': ['-5', '-2.5', '0', '+2.5', '+5', '+7.5'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_head_v40',
    label: 'Heads — V40 CoCr',
    fixationGroups: null,
    rowLabel: 'Diameter',
    sizeLabel: '',
    variants: ['22mm', '28mm', '32mm', '36mm', '40mm'],
    sizes: ['-4', '0', '+3', '+8', '+10', '+12'],
    sizesByVariant: {
      '22mm': ['0', '+3', '+8'],
      '28mm': ['+8'],
      '32mm': ['+8', '+12'],
      '36mm': ['+10'],
      '40mm': ['-4', '+8', '+12'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_head_universal',
    label: 'Heads — Universal',
    fixationGroups: null,
    rowLabel: 'Type',
    sizeLabel: '',
    variants: ['delta_universal_40mm', 'v40_adapter_sleeve'],
    sizes: ['-2.5', '0', '+4'],
    sizesByVariant: {
      'delta_universal_40mm': ['0'],
      'v40_adapter_sleeve': ['-2.5', '0', '+4'],
    } as Record<string, string[]>,
  },
  {
    id: 'hip_screw',
    label: 'Screws',
    fixationGroups: null,
    rowLabel: 'Type',
    sizeLabel: 'mm',
    variants: ['hex_6_5mm', 'torx_6_5mm'],
    sizes: ['15', '16', '20', '25', '30', '35', '40', '45', '50', '55', '60'],
    sizesByVariant: {
      'hex_6_5mm': ['15', '20', '25', '30', '35', '40', '45', '50', '55', '60'],
      'torx_6_5mm': ['16', '20', '25', '30', '35', '40', '45', '50', '55', '60'],
    } as Record<string, string[]>,
  },
] as const

export type HipSection = (typeof HIP_SECTIONS)[number]
